# Generated by Django 5.0.3 on 2024-05-20 07:29

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=225)),
                ('lastname', models.CharField(max_length=225)),
                ('age', models.IntegerField()),
                ('parentsfirstname', models.CharField(max_length=225)),
                ('parentslastname', models.CharField(max_length=225)),
                ('city', models.CharField(max_length=225)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('q1', models.CharField(max_length=225)),
                ('q2', models.CharField(max_length=225)),
                ('q3', models.CharField(max_length=225)),
                ('q4', models.CharField(max_length=225)),
                ('q5', models.CharField(max_length=225)),
                ('q6', models.CharField(max_length=225)),
                ('q7', models.CharField(max_length=225)),
                ('q8', models.CharField(max_length=225)),
                ('q9', models.CharField(max_length=225)),
                ('q10', models.CharField(max_length=225)),
                ('q11', models.CharField(max_length=225)),
                ('q12', models.CharField(max_length=225)),
                ('q13', models.CharField(max_length=225)),
                ('q14', models.CharField(max_length=225)),
                ('q15', models.CharField(max_length=225)),
                ('q16', models.CharField(max_length=225)),
                ('q17', models.CharField(max_length=225)),
                ('q18', models.CharField(max_length=225)),
                ('q19', models.CharField(max_length=225)),
                ('q20', models.CharField(max_length=225)),
                ('q21', models.CharField(max_length=225)),
                ('q22', models.CharField(max_length=225)),
                ('q23', models.CharField(max_length=225)),
                ('q24', models.CharField(max_length=225)),
                ('q25', models.CharField(max_length=225)),
                ('q26', models.CharField(max_length=225)),
                ('q27', models.CharField(max_length=225)),
                ('q28', models.CharField(max_length=225)),
            ],
        ),
    ]
